apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    tier: backend
    component: backend
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      component: backend
      project: expense 
  template:
    metadata:
      labels:
        tier: backend
        component: backend
        project: expense 
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup db-dev.daws78s.online; do echo waiting for myservice; sleep 2; done"]
      containers:
      - name: backend
        image: sky1ger/backend:v1.0
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        envFrom:
          - configMapRef:
              name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    tier: backend
    component: backend
    project: expense 
  ports:
  - protocol: TCP
    port: 8080 #serviceport differs from target port
    targetPort: 8080