apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense-namespace
  labels:
    tier: mysql
    component: mysql
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: mysql
      component: mysql
      project: expense 
  template:
    metadata:
      labels:
        tier: mysql
        component: mysql
        project: expense 
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense-namespace
spec:
  selector:
    tier: mysql
    component: mysql
    project: expense 
  ports:
  - protocol: TCP
    port: 3306 #serviceport differs from target port
    targetPort: 3306